---
title: "Glossary"
output: 
  html_document: 
    theme: cerulean
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

## C

<details>
  <summary>Cumulative Distribution Function</summary>

Source: DataCamp – Exploratory Data Analysis in Python 
Source: empiricaldist package 

**Notes** 

For a given value of x, it tells you the probability of getting something <= x 

Example computing the empirical cdf 
```
def ecdf(data): 

    """Compute ECDF for a one-dimensional array of measurements.""" 

    # Number of data points: n 
    n = len(data) 
    
    # x-data for the ECDF: x 
    x = np.sort(data) 
    
    # y-data for the ECDF: y 
    y = np.arange(1, n + 1) / n 
    
    return x, y 
```
</details>

# K

<details>
  <summary>Kernel Density Function</summary>
 Source: DataCamp – Exploratory Data Analysis in Python 

**Notes** 

This is used to get from a PMF to a PDF 

PMF, CDF, KDE
* Use CDFs for exploration
* Use PMFs if there are a small number of unique values
* Use KDE if there are a lot of values  
</details>

## N

<details>
  <summary>Normalize</summary>
 Source: DataCamp – Exploratory Data Analysis in Python 

**Notes** 
* This actually means to add up to 1 
</details>


## P

<details>
  <summary>Probability Distribution Function </summary>

Source: DataCamp – Exploratory Data Analysis in Python 

</details>

<details>
  <summary>Probability Mass Function</summary>

Source: Datacamp – Exploratory Data Analysis 
Source: empiricaldist package 

**Notes** 

* Introduced as another way of thinking about distributions 
* It basically takes the percentage of the whole and plots it using something like matplotlib.pyplot.bar 
* Advantageous because it shows all unique values as opposed to bins 
* PDF is the continuous analog to the PMF 

</details>


  


