---
title: "Binomial Tests"
output: 
  html_document: 
    theme: cerulean
---

----

----


### Binomial Test {.tabset .tabset-fade .tabset-pills}

The simplest form of statistical analysis is the binomial distribution. It's foundational in understanding higher level concepts.


A binomial test is used when you are asking how likely an outcome is and there are only two outcomes. 

#### Overview 

<div style="padding-left:125px;">
Here are the required assumptions for a binomial distribution:

1. Fixed number of trials
2. Independent trials
3. Two different classifications
4. The probability of success stays the same for all trials

And here is my source: [When Do You Use a Binomial Distribution?](https://www.thoughtco.com/when-to-use-binomial-distribution-3126596)


**Hypotheses** 

<div style="padding-left:15px;">
$H_0: \mu = \text{some number}$

$H_a: \mu \ \left\{\underset{<}{\stackrel{>}{\neq}}\right\} \ \text{some number}$
</div>

**Examples**: [MyKaggleNotebook - Fantasy Football Stats](https://www.kaggle.com/amartinson193/using-stats-to-determine-skill-in-fantasy-football)

</div>



----

#### Python Instructions

<div style="padding-left:125px;">

**Scipy**    
    
`scipy.stats.binom_test(x, n=None, p=0.5, alternative='two-sided')`        
---- [Docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom_test.html )   
   
**Numpy**   
   
`numpy.random.binomial(n, p, size=None)`         
---- [Docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html?highlight=random%20binomial#numpy.random.binomial)   

  * **Notes**    
    * It is the number of successes over n trials     
    
  * **Example**
  
  
        n, p = 10, .5  # number of trials, probability of each trial     
        >>> s = np.random.binomial(n, p, 1000)     
        # result of flipping a coin 10 times, tested 1000 times.    
    
</div>


----

#### Explanation

<div style="padding-left:125px;">

Nothing here for now, refer back to the Kaggle article for a thorough explanation

</div>

----




<footer></footer>


